#pragma once

#include <AP_HAL/AP_HAL_Boards.h>
#include <AP_RangeFinder/AP_RangeFinder_config.h>

#ifndef HAL_PROXIMITY_ENABLED
#define HAL_PROXIMITY_ENABLED (!HAL_MINIMIZE_FEATURES && BOARD_FLASH_SIZE > 1024)
#endif

#ifndef AP_PROXIMITY_BACKEND_DEFAULT_ENABLED
#define AP_PROXIMITY_BACKEND_DEFAULT_ENABLED HAL_PROXIMITY_ENABLED
#endif

#ifndef AP_PROXIMITY_RANGEFINDER_ENABLED
#define AP_PROXIMITY_RANGEFINDER_ENABLED (AP_RANGEFINDER_ENABLED && AP_PROXIMITY_BACKEND_DEFAULT_ENABLED)
#endif
